on: [push]
jobs:
  build:
    name: Auto Deploy Trigger Via Tailnet Tunnel
    runs-on: ubuntu-latest
    steps:
      - name: Connect runner to tailnet
        uses: tailscale/github-action@v3
        with:
          authKey:  ${{ secrets.TAILSCALE_AUTHKEY }}
      
      - name: Kick off Coolify deploy
        run: |
          curl -X POST \
            "http://100.126.192.41:8000/api/v1/deploy?uuid=lwok808s0cooc4g4c044cw0k&force=false"
